### ISSUE TITLE
Upgrade to latest version

### ISSUE THREAD

**Issue by cyclops24** [sebakerckhof/meteor-ionic-sass#1]
Hi @sebakerckhof ,
Do you have any plan to upgrade this package to latest version (1.2.4)?

**Comment by JoeyAndres** [comment]
@cyclops24 See https://github.com/JoeyAndres/meteoric-sass, it is a fork of ionic 1.2.4. Not yet documented. @sebakerckhof have a non-pushed commit imo, caused I can't just add this to my package directory and make this work.

**Comment by JoeyAndres** [comment]
@cyclops24 Never mind, I just saw the update.

**Comment by cyclops24** [comment]
Thanks for your attention @JoeyAndres. :+1:

**Comment by sebakerckhof** [comment]
Yeah, I added version 1.2.4. 
But I'm not actively maintaining this package, since I'm not using it myself anymore. 
Anyway, with Meteor 1.3, you should be able to use it from NPM directly anyway.
